Feature shop management
Management-Of-Staff/client pull request #17
Opened 2022-12-28 15:58 UTC by thsamajiki

(오너) 매장관리 레이아웃 1차 작업

2022-12-28 15:58 UTC, thsamajiki commented
커밋 내용에 폰트 사이즈를 dimens 폴더에 추가했다는게 누락됐습니다;;

확인하시고 코드리뷰 부탁드립니다.

2022-12-28 16:05 UTC, wldsbs requested changes
.idea 폴더 빼고 다시 올려주실수 있을까요??

2022-12-29 05:12 UTC, thsamajiki commented
커밋했습니다.

2022-12-29 09:40 UTC, wldsbs approved these changes

2022-12-29 09:41 UTC, merged