Feat/mclm 160 todolist api
Management-Of-Staff/client pull request #64
Opened 2023-02-24 15:40 UTC by thsamajiki

api 연동 부분 수정했습니다.
매장 목록 불러오기 잘 됩니다

2023-02-25 03:05 UTC, wldsbs requested changes
수정 부탁드립니다

2023-02-25 03:05 UTC, wldsbs commented on app/src/main/java/myapplication/second/workinghourmanagement/store/OwnerStoreRegistrationActivity.kt
> +        val token = MyApplication.prefs.getString("accessToken")
토큰은 사용하지않으니 지워주세요

2023-02-25 03:05 UTC, wldsbs commented on app/src/main/java/myapplication/second/workinghourmanagement/store/todo_list/OwnerModifyStaffTodoActivity.kt
> +        val storeId = MyApplication.prefs.getString("storeId").length
length붙이신 이유가 뭔가요?

2023-02-26 04:50 UTC, thsamajiki commented on app/src/main/java/myapplication/second/workinghourmanagement/store/OwnerStoreRegistrationActivity.kt
> +        val token = MyApplication.prefs.getString("accessToken")
네

2023-02-26 04:50 UTC, thsamajiki commented on app/src/main/java/myapplication/second/workinghourmanagement/store/todo_list/OwnerModifyStaffTodoActivity.kt
> +        val storeId = MyApplication.prefs.getString("storeId").length
임시로 붙인건데 수정할 게획입니다

2023-02-26 04:50 UTC, thsamajiki commented on app/src/main/java/myapplication/second/workinghourmanagement/store/todo_list/OwnerModifyStaffTodoActivity.kt
> +        val storeId = MyApplication.prefs.getString("storeId").length
다음 pr에 수정해서 올릴게요

2023-02-26 12:15 UTC, wldsbs requested changes

2023-02-26 12:15 UTC, wldsbs commented on app/src/main/java/myapplication/second/workinghourmanagement/store/todo_list/OwnerPostStaffTodoActivity.kt
> +        val storeId = MyApplication.prefs.getString("storeId").length
지워주세요 :)

2023-02-26 12:46 UTC, thsamajiki commented on app/src/main/java/myapplication/second/workinghourmanagement/store/todo_list/OwnerPostStaffTodoActivity.kt
> +        val storeId = MyApplication.prefs.getString("storeId").length
다음 pr에서 작업하겠습니다

2023-02-26 13:12 UTC, wldsbs commented on app/src/main/java/myapplication/second/workinghourmanagement/store/todo_list/OwnerModifyStaffTodoActivity.kt
> +        val storeId = MyApplication.prefs.getString("storeId").length
아니요 수정하셔야죵

2023-02-26 13:13 UTC, wldsbs commented
@thsamajiki 수정 부탁...드려요..

2023-02-26 13:17 UTC, wldsbs commented
그리고 호섭님 앞으로 코드리뷰 완료하고, 머지는 pr올린사람이 직접 하는걸로 할게요!

2023-02-26 13:23 UTC, wldsbs requested changes

2023-02-26 13:23 UTC, wldsbs commented on app/src/main/java/myapplication/second/workinghourmanagement/store/todo_list/OwnerPostStaffTodoActivity.kt
> +        val storeId = MyApplication.prefs.getString("storeId").length
필요없는데 굳이 남길 필요는 없을 것 같아요!

2023-02-26 14:30 UTC, thsamajiki commented
> 그리고 호섭님 앞으로 코드리뷰 완료하고, 머지는 pr올린사람이 직접 하는걸로 할게요!

논의를 하고 정하면 좋겠습니다. 그렇게 하는게 좋은 이유가 뭔가요?

2023-02-26 14:31 UTC, thsamajiki commented on app/src/main/java/myapplication/second/workinghourmanagement/store/todo_list/OwnerPostStaffTodoActivity.kt
> +        val storeId = MyApplication.prefs.getString("storeId").length
할일 등록하는데 storeId가 필요한데, 값을 넣는것은 다음 pr에서 작업할게요

2023-02-26 14:33 UTC, wldsbs commented on app/src/main/java/myapplication/second/workinghourmanagement/store/todo_list/OwnerPostStaffTodoActivity.kt
> +        val storeId = MyApplication.prefs.getString("storeId").length
제가 말한건 length 지워달라는거였어요!

2023-02-26 14:53 UTC, wldsbs commented
아 저희는 지금 코드리뷰 받을 사람이 1명이라서 괜찮긴한데, 실제 현업에서는 리뷰어가 많은 경우가 대다수라서 pr올린 사람이 머지합니다. 그래서 그렇게 해보는 건 어떨까 해서여

2023-02-27 11:05 UTC, wldsbs approved these changes
현재 develop 브랜치에 호섭님이 담당하신 부분(store, todo) 가 에러나서 일단 그냥 머지할게요

2023-02-27 11:05 UTC, merged